### ISSUE TITLE
table-refactoring (styling column with, etc.)

### ISSUE THREAD

**Issue by fabian-urner** [volo-db/volodb-frontend#175]

**Comment by Artromi** [comment]
# todo
- [x] table fixed, first column width fixed, td truncate against overflowing (alternative: overflow-x-auto or scroll)
- [ ] fix last td (align icon) -> false aligned since 'table-fixed'
- [ ] pagination shrink and grow aligned?
- [ ] Project table, notes table, documents table
